services:
  db:
    image: postgres:16
    container_name: vertex-db
    env_file: 
      - ./dev.env
    ports:
      - "5432:5432"
    volumes:
      - vertex_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: .
    container_name: vertex-backend
    env_file:
      - ./dev.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python -c 'from app.db.database import create_tables; create_tables()' &&
             uvicorn app.main:app --host ${UVICORN_HOST:-0.0.0.0} --port ${UVICORN_PORT:-8000} --reload"

volumes:
  vertex_pgdata: