from __future__ import annotations

from collections import defaultdict
from typing import Dict, List, Tuple

from app.services.extractor.normalizer import normalize_key


ALIAS_PAIRS: List[Tuple[str, str]] = [
    # Amount
    ("importe", "amount"),
    ("importe total", "amount"),
    ("importe transferencia", "amount"),
    ("importe acreditado", "amount"),
    ("importe debitado", "amount"),
    ("importe transferido", "amount"),
    ("importe operacion", "amount"),
    ("importe operado", "amount"),
    ("monto", "amount"),
    ("monto total", "amount"),
    ("monto acreditado", "amount"),
    ("monto debitado", "amount"),
    ("monto transferido", "amount"),
    ("total", "amount"),
    ("total transferencia", "amount"),
    ("valor", "amount"),
    ("dinero", "amount"),
    ("suma", "amount"),
    ("cantidad", "amount"),
    ("deposito", "amount"),
    ("extraccion", "amount"),
    ("retiro", "amount"),
    ("debe", "amount"),
    ("haber", "amount"),

    # Transaction ID
    ("numero de transaccion", "trx_id"),
    ("número de transacción", "trx_id"),
    ("transaccion numero", "trx_id"),
    ("transacción número", "trx_id"),
    ("transaccion id", "trx_id"),
    ("id transaccion", "trx_id"),
    ("id transacción", "trx_id"),
    ("id operacion", "trx_id"),
    ("id operación", "trx_id"),
    ("numero operacion", "trx_id"),
    ("número operación", "trx_id"),
    ("numero de operacion", "trx_id"),
    ("número de operación", "trx_id"),
    ("nro operacion", "trx_id"),
    ("nro de operacion", "trx_id"),
    ("operacion", "trx_id"),
    ("operación", "trx_id"),
    ("codigo operacion", "trx_id"),
    ("código operación", "trx_id"),
    ("codigo transaccion", "trx_id"),
    ("codigo movimiento", "trx_id"),
    ("codigo comprobante", "trx_id"),
    ("comprobante", "trx_id"),
    ("numero comprobante", "trx_id"),
    ("comprobante numero", "trx_id"),
    ("referencia", "trx_id"),
    ("referencia operacion", "trx_id"),
    ("referencia transaccion", "trx_id"),
    ("referencia transferencia", "trx_id"),
    ("numero referencia", "trx_id"),
    ("nro referencia", "trx_id"),
    ("ticket", "trx_id"),
    ("recibo", "trx_id"),
    ("voucher", "trx_id"),
    ("numero de operacion de mercado pago", "trx_id"),
    ("número de operación de mercado pago", "trx_id"),
    ("id transferencia", "trx_id"),
    ("codigo transferencia", "trx_id"),

    # Date / time
    ("fecha y hora", "date"),
    ("fecha hora", "date"),
    ("fecha hora operacion", "date"),
    ("fecha operacion", "date"),
    ("fecha operación", "date"),
    ("fecha transferencia", "date"),
    ("fecha acreditacion", "date"),
    ("fecha acreditación", "date"),
    ("fecha debito", "date"),
    ("fecha débito", "date"),
    ("fecha transaccion", "date"),
    ("fecha transacción", "date"),
    ("fecha movimiento", "date"),
    ("fecha efectiva", "date"),
    ("fecha liquidacion", "date"),
    ("fecha liquidación", "date"),
    ("fecha contable", "date"),
    ("fecha procesamiento", "date"),
    ("fecha archivo", "date"),
    ("filename datetime", "date"),
    ("fecha", "date"),
    ("hora", "time"),
    ("hora operacion", "time"),
    ("hora operación", "time"),
    ("hora transferencia", "time"),
    ("hora transaccion", "time"),
    ("hora transacción", "time"),

    # Sender
    ("nombre originante", "emisor_name"),
    ("nombre origen", "emisor_name"),
    ("titular origen", "emisor_name"),
    ("cuenta origen titular", "emisor_name"),
    ("propietario cuenta origen", "emisor_name"),
    ("ordenante", "emisor_name"),
    ("remitente", "emisor_name"),
    ("emisor", "emisor_name"),
    ("origen", "emisor_name"),
    ("remitente nombre", "emisor_name"),
    ("nombre remitente", "emisor_name"),
    ("cliente origen", "emisor_name"),
    ("solicitante", "emisor_name"),

    # Sender document
    ("documento originante", "emisor_cuit"),
    ("documento origen", "emisor_cuit"),
    ("cuit originante", "emisor_cuit"),
    ("cuil originante", "emisor_cuit"),
    ("dni originante", "emisor_cuit"),
    ("cuit ordenante", "emisor_cuit"),
    ("cuil ordenante", "emisor_cuit"),
    ("dni ordenante", "emisor_cuit"),
    ("documento ordenante", "emisor_cuit"),
    ("cuit emisor", "emisor_cuit"),
    ("dni emisor", "emisor_cuit"),
    ("cuil emisor", "emisor_cuit"),
    ("documento emisor", "emisor_cuit"),
    ("numero documento emisor", "emisor_cuit"),
    ("numero dni emisor", "emisor_cuit"),
    ("numero cuit emisor", "emisor_cuit"),
    ("numero cuil emisor", "emisor_cuit"),

    # Sender account
    ("cuenta origen", "emisor_cbu"),
    ("cuenta origen cbu", "emisor_cbu"),
    ("cbu origen", "emisor_cbu"),
    ("cbu cuenta origen", "emisor_cbu"),
    ("cvu origen", "emisor_cbu"),
    ("alias origen", "emisor_cbu"),
    ("cta origen", "emisor_cbu"),
    ("numero cuenta origen", "emisor_cbu"),
    ("cuenta bancaria origen", "emisor_cbu"),
    ("cbu emisor", "emisor_cbu"),
    ("cvu emisor", "emisor_cbu"),
    ("alias emisor", "emisor_cbu"),
    ("cuenta emisor", "emisor_cbu"),
    ("numero cuenta emisor", "emisor_cbu"),

    # Receiver
    ("envio de dinero a", "receptor_name"),
    ("envío de dinero a", "receptor_name"),
    ("nombre destinatario", "receptor_name"),
    ("destinatario", "receptor_name"),
    ("beneficiario", "receptor_name"),
    ("receptor", "receptor_name"),
    ("receptor final", "receptor_name"),
    ("destino", "receptor_name"),
    ("beneficiario nombre", "receptor_name"),
    ("nombre beneficiario", "receptor_name"),
    ("cliente destino", "receptor_name"),
    ("titular destino", "receptor_name"),
    ("propietario cuenta destino", "receptor_name"),
    ("proveedor", "receptor_name"),
    ("vendedor", "receptor_name"),

    # Receiver document
    ("documento destinatario", "receptor_cuit"),
    ("documento destino", "receptor_cuit"),
    ("cuit destinatario", "receptor_cuit"),
    ("cuil destinatario", "receptor_cuit"),
    ("dni destinatario", "receptor_cuit"),
    ("cuit beneficiario", "receptor_cuit"),
    ("cuil beneficiario", "receptor_cuit"),
    ("dni beneficiario", "receptor_cuit"),
    ("documento beneficiario", "receptor_cuit"),
    ("cuit receptor", "receptor_cuit"),
    ("dni receptor", "receptor_cuit"),
    ("cuil receptor", "receptor_cuit"),
    ("documento receptor", "receptor_cuit"),
    ("numero documento receptor", "receptor_cuit"),
    ("numero dni receptor", "receptor_cuit"),
    ("numero cuit receptor", "receptor_cuit"),
    ("numero cuil receptor", "receptor_cuit"),

    # Receiver account
    ("cuenta destino", "receptor_cbu"),
    ("cuenta destino cbu", "receptor_cbu"),
    ("cbu destino", "receptor_cbu"),
    ("cbu cuenta destino", "receptor_cbu"),
    ("cvu destino", "receptor_cbu"),
    ("alias destino", "receptor_cbu"),
    ("cta destino", "receptor_cbu"),
    ("cuenta credito", "receptor_cbu"),
    ("cuenta crédito", "receptor_cbu"),
    ("numero cuenta destino", "receptor_cbu"),
    ("cuenta bancaria destino", "receptor_cbu"),
    ("cbu receptor", "receptor_cbu"),
    ("cvu receptor", "receptor_cbu"),
    ("alias receptor", "receptor_cbu"),
    ("cuenta receptor", "receptor_cbu"),
    ("numero cuenta receptor", "receptor_cbu"),

    # Wallet generic fields
    ("cvu", "wallet_cvu"),
    ("alias", "wallet_cvu"),
    ("alias cvu", "wallet_cvu"),
    ("cvu cuenta", "wallet_cvu"),
    ("cuenta cvu", "wallet_cvu"),
    ("cuit cuil", "wallet_cuit"),
    ("cuit/cuil", "wallet_cuit"),
    ("cuitcuil", "wallet_cuit"),
    ("cuit", "wallet_cuit"),
    ("cuil", "wallet_cuit"),
    ("dni", "wallet_cuit"),
    ("documento", "wallet_cuit"),
    ("documento titular", "wallet_cuit"),
    ("documento usuario", "wallet_cuit"),
]


def _build_aliases() -> Dict[str, str]:
    grouped: Dict[str, set[str]] = defaultdict(set)

    for raw_key, target in ALIAS_PAIRS:
        grouped[normalize_key(raw_key)].add(target)

    conflicts = {key: sorted(targets) for key, targets in grouped.items() if len(targets) > 1}
    if conflicts:
        raise ValueError(f"Conflicting aliases detected: {conflicts}")

    return {key: next(iter(targets)) for key, targets in grouped.items()}


KEY_ALIASES = _build_aliases()
